### PR TITLE
Update README.asciidoc

### PR DESCRIPTION
**Pull request by isapir**
1) added path for Windows since / does not work in command prompt
2) placed "check" in its own section, as currently it is confusing.  "check" should not be part of the "installation".

### CODE REVIEW

**Comment by clintongormley** [comment]
Hi @TwentyOneSolutions 

Thanks for the PR.  Please could I ask you to sign the CLA so that I can merge it in?
http://www.elasticsearch.org/contributor-agreement/

**Comment by isapir** [comment]
done

**Comment by clintongormley** [comment]
Hmm sorry @TwentyOneSolutions but I can't find the signed CLA.  Did you use the same email address that you use on github?

**Comment by isapir** [comment]
yes, and also set my username as TwentyOneSolutions

you can just update the docs yourself according to my changes without pulling the request if you want.

**Comment by clintongormley** [comment]
thanks @TwentyOneSolutions

**Pull request closed without merging**
